name: NS2d
file: finetune.py

model: Nestor
dataset: ns2d
use_writer: True
res: 128
modes: 32
patch_size: 8
lr: 0.001
lr_method: cycle
warmup_epochs: 40
step_size: 100
step_gamma: 0.5
epochs: 200
noise_scale: 0.0005
T_ar: 1
use_ln: 1
normalize: 0
T_bundle: 1
grad_clip: 10000.0
beta1: 0.9
beta2: 0.9
n_channels: 4
n_class: 12



##########################################
############ Tiny models
##########################################
resume_path: '/zxy/nestor/logs_pretrain/Nestor_ns2d_0812_17_36_33:Tiny_12_129288/model_19.pth'
load_components: ['all']
n_layers: 4
n_blocks: 4
mlp_ratio: 1
width: 512

###################################################### Data paths
tasks:
  comment: ['_ns2d_fno_1e-5_'] 
  epochs: [500] 
  warmup_epochs: [20]  # 40
  batch_size: [32]
  noise_scale: [0.0]

  train_paths: [
    # 'ns2d_fno_1e-5' # over
    # 'ns2d_fno_1e-4'  # ing 
    # 'ns2d_fno_1e-3'  # over
    # 'ns2d_pdb_M1_eta1e-1_zeta1e-1'  # over
    # 'ns2d_pdb_M1_eta1e-2_zeta1e-2'   # over
    # 'ns2d_pdb_M1e-1_eta1e-1_zeta1e-1'  #ing
    # 'ns2d_pdb_M1e-1_eta1e-2_zeta1e-2',  # ing
    # 'swe_pdb'  # over
    # 'dr_pdb'  # ing
    # 'ns2d_pda'  # over
    # 'ns2d_cond_pda'  # ing
    # 'cfdbench'  # ing
    # 'ns2d_pdb_M1e-1_eta1e-8_zeta1e-8_turb_512'
    # 'ns2d_pdb_M1_eta1e-8_zeta1e-8_turb_512'
    # 'Wave-Layer'
    # 'Wave-Gauss'
    # 'EAR5'
  ]
  test_paths: [
   # 'ns2d_fno_1e-5'
    # 'ns2d_fno_1e-4'
    # 'ns2d_fno_1e-3'
    # 'ns2d_pdb_M1_eta1e-1_zeta1e-1'
    # 'ns2d_pdb_M1_eta1e-2_zeta1e-2'
    # 'ns2d_pdb_M1e-1_eta1e-1_zeta1e-1'
    # 'ns2d_pdb_M1e-1_eta1e-2_zeta1e-2'
    # 'swe_pdb'
    # 'dr_pdb'
    # 'ns2d_pda' 
    # 'ns2d_cond_pda'  
    # 'cfdbench'
    # 'ns2d_pdb_M1e-1_eta1e-8_zeta1e-8_turb_512'
    # 'ns2d_pdb_M1_eta1e-8_zeta1e-8_turb_512'
    # 'Wave-Layer'
    # 'Wave-Gauss'
    # 'EAR5'
  ]
  ntrain_list: [
    # 1000
    # 9800
    # 1000
    # 9000
    # 9000
    # 9000
    # # 9000,
    # 900
    # 900
    # 6500
    # 3103
    # 9000
    # 900
    # 90

    10212
    # 1449
  ]